// <auto-generated />
using System;
using ArrayTester;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArrayTester.Migrations
{
    [DbContext(typeof(ArrayContext))]
    [Migration("20230730173414_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArrayTester.PartialData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Value_0")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Value_1")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Value_2")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Value_3")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Value_4")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Value_5")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Value_6")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Value_7")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("PortionData");
                });

            modelBuilder.Entity("ArrayTester.WholeArray", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("ByteArray")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("Array");
                });
#pragma warning restore 612, 618
        }
    }
}
